System time: 11:17:43
Argument command line: -i /home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/example_data/Rf00001.fa -data_gen

DEBUG:root:Failed to generate control alignment for: _align_2_1
 Empty file? 

DEBUG:root:Failed to generate control alignment for: _align_2_1
 Empty file? 

Failed to generate control alignment for: _align_2_1
 Empty file? 

MOST RECENT TRACEBACK: 
  File "/home/christopher/anaconda3/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
   File "/home/christopher/anaconda3/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/__main__.py", line 50, in <module>
    main()
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/__main__.py", line 30, in main
    svhip.create_data_set()
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/svhip_object.py", line 46, in create_data_set
    generate_data.testset_cr(self.func_argx, self.inputfile, self.outfile, self.function_log)
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/data_gen/generate_data.py", line 382, in testset_cr
    outfile = build_data(argx, inputfile, outfile, function_log)
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/data_gen/generate_data.py", line 233, in build_data
    create_training_set(inputfile, parameters, outfile, 1, function_log)
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/data_gen/generate_data.py", line 96, in create_training_set
    function_log.write_log("Failed to generate control alignment for: " + aln.windows[i].identifier + '\n Empty file? \n')
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/logger/logger.py", line 31, in write_log
    self.begin_traceback(self.get_log_name())
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/logger/logger.py", line 43, in begin_traceback
    rep_lg = traceback.format_stack()

DEBUG:root:Failed to generate control alignment for: _align_2_2
 Empty file? 

DEBUG:root:Failed to generate control alignment for: _align_2_2
 Empty file? 

Failed to generate control alignment for: _align_2_2
 Empty file? 

MOST RECENT TRACEBACK: 
  File "/home/christopher/anaconda3/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
   File "/home/christopher/anaconda3/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/__main__.py", line 50, in <module>
    main()
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/__main__.py", line 30, in main
    svhip.create_data_set()
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/svhip_object.py", line 46, in create_data_set
    generate_data.testset_cr(self.func_argx, self.inputfile, self.outfile, self.function_log)
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/data_gen/generate_data.py", line 382, in testset_cr
    outfile = build_data(argx, inputfile, outfile, function_log)
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/data_gen/generate_data.py", line 233, in build_data
    create_training_set(inputfile, parameters, outfile, 1, function_log)
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/data_gen/generate_data.py", line 96, in create_training_set
    function_log.write_log("Failed to generate control alignment for: " + aln.windows[i].identifier + '\n Empty file? \n')
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/logger/logger.py", line 31, in write_log
    self.begin_traceback(self.get_log_name())
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/logger/logger.py", line 43, in begin_traceback
    rep_lg = traceback.format_stack()

DEBUG:root:Failed to generate control alignment for: _align_2_3
 Empty file? 

DEBUG:root:Failed to generate control alignment for: _align_2_3
 Empty file? 

Failed to generate control alignment for: _align_2_3
 Empty file? 

MOST RECENT TRACEBACK: 
  File "/home/christopher/anaconda3/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
   File "/home/christopher/anaconda3/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/__main__.py", line 50, in <module>
    main()
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/__main__.py", line 30, in main
    svhip.create_data_set()
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/svhip_object.py", line 46, in create_data_set
    generate_data.testset_cr(self.func_argx, self.inputfile, self.outfile, self.function_log)
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/data_gen/generate_data.py", line 382, in testset_cr
    outfile = build_data(argx, inputfile, outfile, function_log)
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/data_gen/generate_data.py", line 233, in build_data
    create_training_set(inputfile, parameters, outfile, 1, function_log)
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/data_gen/generate_data.py", line 96, in create_training_set
    function_log.write_log("Failed to generate control alignment for: " + aln.windows[i].identifier + '\n Empty file? \n')
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/logger/logger.py", line 31, in write_log
    self.begin_traceback(self.get_log_name())
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/logger/logger.py", line 43, in begin_traceback
    rep_lg = traceback.format_stack()

DEBUG:root:Failed to generate control alignment for: _align_2_4
 Empty file? 

DEBUG:root:Failed to generate control alignment for: _align_2_4
 Empty file? 

Failed to generate control alignment for: _align_2_4
 Empty file? 

MOST RECENT TRACEBACK: 
  File "/home/christopher/anaconda3/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
   File "/home/christopher/anaconda3/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/__main__.py", line 50, in <module>
    main()
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/__main__.py", line 30, in main
    svhip.create_data_set()
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/svhip_object.py", line 46, in create_data_set
    generate_data.testset_cr(self.func_argx, self.inputfile, self.outfile, self.function_log)
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/data_gen/generate_data.py", line 382, in testset_cr
    outfile = build_data(argx, inputfile, outfile, function_log)
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/data_gen/generate_data.py", line 233, in build_data
    create_training_set(inputfile, parameters, outfile, 1, function_log)
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/data_gen/generate_data.py", line 96, in create_training_set
    function_log.write_log("Failed to generate control alignment for: " + aln.windows[i].identifier + '\n Empty file? \n')
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/logger/logger.py", line 31, in write_log
    self.begin_traceback(self.get_log_name())
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/logger/logger.py", line 43, in begin_traceback
    rep_lg = traceback.format_stack()

DEBUG:root:Failed to generate control alignment for: _align_2_5
 Empty file? 

DEBUG:root:Failed to generate control alignment for: _align_2_5
 Empty file? 

Failed to generate control alignment for: _align_2_5
 Empty file? 

MOST RECENT TRACEBACK: 
  File "/home/christopher/anaconda3/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
   File "/home/christopher/anaconda3/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/__main__.py", line 50, in <module>
    main()
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/__main__.py", line 30, in main
    svhip.create_data_set()
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/svhip_object.py", line 46, in create_data_set
    generate_data.testset_cr(self.func_argx, self.inputfile, self.outfile, self.function_log)
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/data_gen/generate_data.py", line 382, in testset_cr
    outfile = build_data(argx, inputfile, outfile, function_log)
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/data_gen/generate_data.py", line 233, in build_data
    create_training_set(inputfile, parameters, outfile, 1, function_log)
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/data_gen/generate_data.py", line 96, in create_training_set
    function_log.write_log("Failed to generate control alignment for: " + aln.windows[i].identifier + '\n Empty file? \n')
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/logger/logger.py", line 31, in write_log
    self.begin_traceback(self.get_log_name())
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/logger/logger.py", line 43, in begin_traceback
    rep_lg = traceback.format_stack()

DEBUG:root:Failed to generate control alignment for: _align_2_6
 Empty file? 

DEBUG:root:Failed to generate control alignment for: _align_2_6
 Empty file? 

Failed to generate control alignment for: _align_2_6
 Empty file? 

MOST RECENT TRACEBACK: 
  File "/home/christopher/anaconda3/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
   File "/home/christopher/anaconda3/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/__main__.py", line 50, in <module>
    main()
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/__main__.py", line 30, in main
    svhip.create_data_set()
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/svhip_object.py", line 46, in create_data_set
    generate_data.testset_cr(self.func_argx, self.inputfile, self.outfile, self.function_log)
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/data_gen/generate_data.py", line 382, in testset_cr
    outfile = build_data(argx, inputfile, outfile, function_log)
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/data_gen/generate_data.py", line 233, in build_data
    create_training_set(inputfile, parameters, outfile, 1, function_log)
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/data_gen/generate_data.py", line 96, in create_training_set
    function_log.write_log("Failed to generate control alignment for: " + aln.windows[i].identifier + '\n Empty file? \n')
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/logger/logger.py", line 31, in write_log
    self.begin_traceback(self.get_log_name())
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/logger/logger.py", line 43, in begin_traceback
    rep_lg = traceback.format_stack()

DEBUG:root:Failed to generate control alignment for: _align_2_7
 Empty file? 

DEBUG:root:Failed to generate control alignment for: _align_2_7
 Empty file? 

Failed to generate control alignment for: _align_2_7
 Empty file? 

MOST RECENT TRACEBACK: 
  File "/home/christopher/anaconda3/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
   File "/home/christopher/anaconda3/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/__main__.py", line 50, in <module>
    main()
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/__main__.py", line 30, in main
    svhip.create_data_set()
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/svhip_object.py", line 46, in create_data_set
    generate_data.testset_cr(self.func_argx, self.inputfile, self.outfile, self.function_log)
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/data_gen/generate_data.py", line 382, in testset_cr
    outfile = build_data(argx, inputfile, outfile, function_log)
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/data_gen/generate_data.py", line 233, in build_data
    create_training_set(inputfile, parameters, outfile, 1, function_log)
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/data_gen/generate_data.py", line 96, in create_training_set
    function_log.write_log("Failed to generate control alignment for: " + aln.windows[i].identifier + '\n Empty file? \n')
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/logger/logger.py", line 31, in write_log
    self.begin_traceback(self.get_log_name())
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/logger/logger.py", line 43, in begin_traceback
    rep_lg = traceback.format_stack()

DEBUG:root:Failed to generate control alignment for: _align_2_8
 Empty file? 

DEBUG:root:Failed to generate control alignment for: _align_2_8
 Empty file? 

Failed to generate control alignment for: _align_2_8
 Empty file? 

MOST RECENT TRACEBACK: 
  File "/home/christopher/anaconda3/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
   File "/home/christopher/anaconda3/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/__main__.py", line 50, in <module>
    main()
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/__main__.py", line 30, in main
    svhip.create_data_set()
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/svhip_object.py", line 46, in create_data_set
    generate_data.testset_cr(self.func_argx, self.inputfile, self.outfile, self.function_log)
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/data_gen/generate_data.py", line 382, in testset_cr
    outfile = build_data(argx, inputfile, outfile, function_log)
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/data_gen/generate_data.py", line 233, in build_data
    create_training_set(inputfile, parameters, outfile, 1, function_log)
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/data_gen/generate_data.py", line 96, in create_training_set
    function_log.write_log("Failed to generate control alignment for: " + aln.windows[i].identifier + '\n Empty file? \n')
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/logger/logger.py", line 31, in write_log
    self.begin_traceback(self.get_log_name())
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/logger/logger.py", line 43, in begin_traceback
    rep_lg = traceback.format_stack()

DEBUG:root:Failed to generate control alignment for: _align_2_9
 Empty file? 

DEBUG:root:Failed to generate control alignment for: _align_2_9
 Empty file? 

Failed to generate control alignment for: _align_2_9
 Empty file? 

MOST RECENT TRACEBACK: 
  File "/home/christopher/anaconda3/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
   File "/home/christopher/anaconda3/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/__main__.py", line 50, in <module>
    main()
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/__main__.py", line 30, in main
    svhip.create_data_set()
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/svhip_object.py", line 46, in create_data_set
    generate_data.testset_cr(self.func_argx, self.inputfile, self.outfile, self.function_log)
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/data_gen/generate_data.py", line 382, in testset_cr
    outfile = build_data(argx, inputfile, outfile, function_log)
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/data_gen/generate_data.py", line 233, in build_data
    create_training_set(inputfile, parameters, outfile, 1, function_log)
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/data_gen/generate_data.py", line 96, in create_training_set
    function_log.write_log("Failed to generate control alignment for: " + aln.windows[i].identifier + '\n Empty file? \n')
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/logger/logger.py", line 31, in write_log
    self.begin_traceback(self.get_log_name())
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/logger/logger.py", line 43, in begin_traceback
    rep_lg = traceback.format_stack()

DEBUG:root:Failed to generate control alignment for: _align_2_10
 Empty file? 

DEBUG:root:Failed to generate control alignment for: _align_2_10
 Empty file? 

Failed to generate control alignment for: _align_2_10
 Empty file? 

MOST RECENT TRACEBACK: 
  File "/home/christopher/anaconda3/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
   File "/home/christopher/anaconda3/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/__main__.py", line 50, in <module>
    main()
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/__main__.py", line 30, in main
    svhip.create_data_set()
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/svhip_object.py", line 46, in create_data_set
    generate_data.testset_cr(self.func_argx, self.inputfile, self.outfile, self.function_log)
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/data_gen/generate_data.py", line 382, in testset_cr
    outfile = build_data(argx, inputfile, outfile, function_log)
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/data_gen/generate_data.py", line 233, in build_data
    create_training_set(inputfile, parameters, outfile, 1, function_log)
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/data_gen/generate_data.py", line 96, in create_training_set
    function_log.write_log("Failed to generate control alignment for: " + aln.windows[i].identifier + '\n Empty file? \n')
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/logger/logger.py", line 31, in write_log
    self.begin_traceback(self.get_log_name())
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/logger/logger.py", line 43, in begin_traceback
    rep_lg = traceback.format_stack()

DEBUG:root:Failed to generate control alignment for: _align_3_1
 Empty file? 

DEBUG:root:Failed to generate control alignment for: _align_3_1
 Empty file? 

Failed to generate control alignment for: _align_3_1
 Empty file? 

MOST RECENT TRACEBACK: 
  File "/home/christopher/anaconda3/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
   File "/home/christopher/anaconda3/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/__main__.py", line 50, in <module>
    main()
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/__main__.py", line 30, in main
    svhip.create_data_set()
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/svhip_object.py", line 46, in create_data_set
    generate_data.testset_cr(self.func_argx, self.inputfile, self.outfile, self.function_log)
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/data_gen/generate_data.py", line 382, in testset_cr
    outfile = build_data(argx, inputfile, outfile, function_log)
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/data_gen/generate_data.py", line 233, in build_data
    create_training_set(inputfile, parameters, outfile, 1, function_log)
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/data_gen/generate_data.py", line 96, in create_training_set
    function_log.write_log("Failed to generate control alignment for: " + aln.windows[i].identifier + '\n Empty file? \n')
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/logger/logger.py", line 31, in write_log
    self.begin_traceback(self.get_log_name())
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/logger/logger.py", line 43, in begin_traceback
    rep_lg = traceback.format_stack()

DEBUG:root:Failed to generate control alignment for: _align_3_2
 Empty file? 

DEBUG:root:Failed to generate control alignment for: _align_3_2
 Empty file? 

Failed to generate control alignment for: _align_3_2
 Empty file? 

MOST RECENT TRACEBACK: 
  File "/home/christopher/anaconda3/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
   File "/home/christopher/anaconda3/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/__main__.py", line 50, in <module>
    main()
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/__main__.py", line 30, in main
    svhip.create_data_set()
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/svhip_object.py", line 46, in create_data_set
    generate_data.testset_cr(self.func_argx, self.inputfile, self.outfile, self.function_log)
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/data_gen/generate_data.py", line 382, in testset_cr
    outfile = build_data(argx, inputfile, outfile, function_log)
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/data_gen/generate_data.py", line 233, in build_data
    create_training_set(inputfile, parameters, outfile, 1, function_log)
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/data_gen/generate_data.py", line 96, in create_training_set
    function_log.write_log("Failed to generate control alignment for: " + aln.windows[i].identifier + '\n Empty file? \n')
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/logger/logger.py", line 31, in write_log
    self.begin_traceback(self.get_log_name())
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/logger/logger.py", line 43, in begin_traceback
    rep_lg = traceback.format_stack()

DEBUG:root:Failed to generate control alignment for: _align_3_3
 Empty file? 

DEBUG:root:Failed to generate control alignment for: _align_3_3
 Empty file? 

Failed to generate control alignment for: _align_3_3
 Empty file? 

MOST RECENT TRACEBACK: 
  File "/home/christopher/anaconda3/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
   File "/home/christopher/anaconda3/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/__main__.py", line 50, in <module>
    main()
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/__main__.py", line 30, in main
    svhip.create_data_set()
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/svhip_object.py", line 46, in create_data_set
    generate_data.testset_cr(self.func_argx, self.inputfile, self.outfile, self.function_log)
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/data_gen/generate_data.py", line 382, in testset_cr
    outfile = build_data(argx, inputfile, outfile, function_log)
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/data_gen/generate_data.py", line 233, in build_data
    create_training_set(inputfile, parameters, outfile, 1, function_log)
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/data_gen/generate_data.py", line 96, in create_training_set
    function_log.write_log("Failed to generate control alignment for: " + aln.windows[i].identifier + '\n Empty file? \n')
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/logger/logger.py", line 31, in write_log
    self.begin_traceback(self.get_log_name())
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/logger/logger.py", line 43, in begin_traceback
    rep_lg = traceback.format_stack()

DEBUG:root:Failed to generate control alignment for: _align_3_4
 Empty file? 

DEBUG:root:Failed to generate control alignment for: _align_3_4
 Empty file? 

Failed to generate control alignment for: _align_3_4
 Empty file? 

MOST RECENT TRACEBACK: 
  File "/home/christopher/anaconda3/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
   File "/home/christopher/anaconda3/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/__main__.py", line 50, in <module>
    main()
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/__main__.py", line 30, in main
    svhip.create_data_set()
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/svhip_object.py", line 46, in create_data_set
    generate_data.testset_cr(self.func_argx, self.inputfile, self.outfile, self.function_log)
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/data_gen/generate_data.py", line 382, in testset_cr
    outfile = build_data(argx, inputfile, outfile, function_log)
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/data_gen/generate_data.py", line 233, in build_data
    create_training_set(inputfile, parameters, outfile, 1, function_log)
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/data_gen/generate_data.py", line 96, in create_training_set
    function_log.write_log("Failed to generate control alignment for: " + aln.windows[i].identifier + '\n Empty file? \n')
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/logger/logger.py", line 31, in write_log
    self.begin_traceback(self.get_log_name())
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/logger/logger.py", line 43, in begin_traceback
    rep_lg = traceback.format_stack()

DEBUG:root:Failed to generate control alignment for: _align_3_5
 Empty file? 

DEBUG:root:Failed to generate control alignment for: _align_3_5
 Empty file? 

Failed to generate control alignment for: _align_3_5
 Empty file? 

MOST RECENT TRACEBACK: 
  File "/home/christopher/anaconda3/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
   File "/home/christopher/anaconda3/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/__main__.py", line 50, in <module>
    main()
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/__main__.py", line 30, in main
    svhip.create_data_set()
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/svhip_object.py", line 46, in create_data_set
    generate_data.testset_cr(self.func_argx, self.inputfile, self.outfile, self.function_log)
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/data_gen/generate_data.py", line 382, in testset_cr
    outfile = build_data(argx, inputfile, outfile, function_log)
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/data_gen/generate_data.py", line 233, in build_data
    create_training_set(inputfile, parameters, outfile, 1, function_log)
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/data_gen/generate_data.py", line 96, in create_training_set
    function_log.write_log("Failed to generate control alignment for: " + aln.windows[i].identifier + '\n Empty file? \n')
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/logger/logger.py", line 31, in write_log
    self.begin_traceback(self.get_log_name())
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/logger/logger.py", line 43, in begin_traceback
    rep_lg = traceback.format_stack()

DEBUG:root:Failed to generate control alignment for: _align_3_6
 Empty file? 

DEBUG:root:Failed to generate control alignment for: _align_3_6
 Empty file? 

Failed to generate control alignment for: _align_3_6
 Empty file? 

MOST RECENT TRACEBACK: 
  File "/home/christopher/anaconda3/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
   File "/home/christopher/anaconda3/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/__main__.py", line 50, in <module>
    main()
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/__main__.py", line 30, in main
    svhip.create_data_set()
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/svhip_object.py", line 46, in create_data_set
    generate_data.testset_cr(self.func_argx, self.inputfile, self.outfile, self.function_log)
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/data_gen/generate_data.py", line 382, in testset_cr
    outfile = build_data(argx, inputfile, outfile, function_log)
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/data_gen/generate_data.py", line 233, in build_data
    create_training_set(inputfile, parameters, outfile, 1, function_log)
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/data_gen/generate_data.py", line 96, in create_training_set
    function_log.write_log("Failed to generate control alignment for: " + aln.windows[i].identifier + '\n Empty file? \n')
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/logger/logger.py", line 31, in write_log
    self.begin_traceback(self.get_log_name())
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/logger/logger.py", line 43, in begin_traceback
    rep_lg = traceback.format_stack()

DEBUG:root:Failed to generate control alignment for: _align_3_7
 Empty file? 

DEBUG:root:Failed to generate control alignment for: _align_3_7
 Empty file? 

Failed to generate control alignment for: _align_3_7
 Empty file? 

MOST RECENT TRACEBACK: 
  File "/home/christopher/anaconda3/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
   File "/home/christopher/anaconda3/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/__main__.py", line 50, in <module>
    main()
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/__main__.py", line 30, in main
    svhip.create_data_set()
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/svhip_object.py", line 46, in create_data_set
    generate_data.testset_cr(self.func_argx, self.inputfile, self.outfile, self.function_log)
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/data_gen/generate_data.py", line 382, in testset_cr
    outfile = build_data(argx, inputfile, outfile, function_log)
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/data_gen/generate_data.py", line 233, in build_data
    create_training_set(inputfile, parameters, outfile, 1, function_log)
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/data_gen/generate_data.py", line 96, in create_training_set
    function_log.write_log("Failed to generate control alignment for: " + aln.windows[i].identifier + '\n Empty file? \n')
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/logger/logger.py", line 31, in write_log
    self.begin_traceback(self.get_log_name())
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/logger/logger.py", line 43, in begin_traceback
    rep_lg = traceback.format_stack()

DEBUG:root:Failed to generate control alignment for: _align_3_8
 Empty file? 

DEBUG:root:Failed to generate control alignment for: _align_3_8
 Empty file? 

Failed to generate control alignment for: _align_3_8
 Empty file? 

MOST RECENT TRACEBACK: 
  File "/home/christopher/anaconda3/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
   File "/home/christopher/anaconda3/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/__main__.py", line 50, in <module>
    main()
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/__main__.py", line 30, in main
    svhip.create_data_set()
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/svhip_object.py", line 46, in create_data_set
    generate_data.testset_cr(self.func_argx, self.inputfile, self.outfile, self.function_log)
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/data_gen/generate_data.py", line 382, in testset_cr
    outfile = build_data(argx, inputfile, outfile, function_log)
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/data_gen/generate_data.py", line 233, in build_data
    create_training_set(inputfile, parameters, outfile, 1, function_log)
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/data_gen/generate_data.py", line 96, in create_training_set
    function_log.write_log("Failed to generate control alignment for: " + aln.windows[i].identifier + '\n Empty file? \n')
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/logger/logger.py", line 31, in write_log
    self.begin_traceback(self.get_log_name())
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/logger/logger.py", line 43, in begin_traceback
    rep_lg = traceback.format_stack()

DEBUG:root:Failed to generate control alignment for: _align_3_9
 Empty file? 

DEBUG:root:Failed to generate control alignment for: _align_3_9
 Empty file? 

Failed to generate control alignment for: _align_3_9
 Empty file? 

MOST RECENT TRACEBACK: 
  File "/home/christopher/anaconda3/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
   File "/home/christopher/anaconda3/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/__main__.py", line 50, in <module>
    main()
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/__main__.py", line 30, in main
    svhip.create_data_set()
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/svhip_object.py", line 46, in create_data_set
    generate_data.testset_cr(self.func_argx, self.inputfile, self.outfile, self.function_log)
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/data_gen/generate_data.py", line 382, in testset_cr
    outfile = build_data(argx, inputfile, outfile, function_log)
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/data_gen/generate_data.py", line 233, in build_data
    create_training_set(inputfile, parameters, outfile, 1, function_log)
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/data_gen/generate_data.py", line 96, in create_training_set
    function_log.write_log("Failed to generate control alignment for: " + aln.windows[i].identifier + '\n Empty file? \n')
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/logger/logger.py", line 31, in write_log
    self.begin_traceback(self.get_log_name())
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/logger/logger.py", line 43, in begin_traceback
    rep_lg = traceback.format_stack()

DEBUG:root:Failed to generate control alignment for: _align_3_10
 Empty file? 

DEBUG:root:Failed to generate control alignment for: _align_3_10
 Empty file? 

Failed to generate control alignment for: _align_3_10
 Empty file? 

MOST RECENT TRACEBACK: 
  File "/home/christopher/anaconda3/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
   File "/home/christopher/anaconda3/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/__main__.py", line 50, in <module>
    main()
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/__main__.py", line 30, in main
    svhip.create_data_set()
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/svhip_object.py", line 46, in create_data_set
    generate_data.testset_cr(self.func_argx, self.inputfile, self.outfile, self.function_log)
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/data_gen/generate_data.py", line 382, in testset_cr
    outfile = build_data(argx, inputfile, outfile, function_log)
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/data_gen/generate_data.py", line 233, in build_data
    create_training_set(inputfile, parameters, outfile, 1, function_log)
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/data_gen/generate_data.py", line 96, in create_training_set
    function_log.write_log("Failed to generate control alignment for: " + aln.windows[i].identifier + '\n Empty file? \n')
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/logger/logger.py", line 31, in write_log
    self.begin_traceback(self.get_log_name())
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/logger/logger.py", line 43, in begin_traceback
    rep_lg = traceback.format_stack()

DEBUG:root:Failed to generate control alignment for: _align_4_1
 Empty file? 

DEBUG:root:Failed to generate control alignment for: _align_4_1
 Empty file? 

Failed to generate control alignment for: _align_4_1
 Empty file? 

MOST RECENT TRACEBACK: 
  File "/home/christopher/anaconda3/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
   File "/home/christopher/anaconda3/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/__main__.py", line 50, in <module>
    main()
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/__main__.py", line 30, in main
    svhip.create_data_set()
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/svhip_object.py", line 46, in create_data_set
    generate_data.testset_cr(self.func_argx, self.inputfile, self.outfile, self.function_log)
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/data_gen/generate_data.py", line 382, in testset_cr
    outfile = build_data(argx, inputfile, outfile, function_log)
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/data_gen/generate_data.py", line 233, in build_data
    create_training_set(inputfile, parameters, outfile, 1, function_log)
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/data_gen/generate_data.py", line 96, in create_training_set
    function_log.write_log("Failed to generate control alignment for: " + aln.windows[i].identifier + '\n Empty file? \n')
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/logger/logger.py", line 31, in write_log
    self.begin_traceback(self.get_log_name())
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/logger/logger.py", line 43, in begin_traceback
    rep_lg = traceback.format_stack()

DEBUG:root:Failed to generate control alignment for: _align_4_2
 Empty file? 

DEBUG:root:Failed to generate control alignment for: _align_4_2
 Empty file? 

Failed to generate control alignment for: _align_4_2
 Empty file? 

MOST RECENT TRACEBACK: 
  File "/home/christopher/anaconda3/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
   File "/home/christopher/anaconda3/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/__main__.py", line 50, in <module>
    main()
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/__main__.py", line 30, in main
    svhip.create_data_set()
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/svhip_object.py", line 46, in create_data_set
    generate_data.testset_cr(self.func_argx, self.inputfile, self.outfile, self.function_log)
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/data_gen/generate_data.py", line 382, in testset_cr
    outfile = build_data(argx, inputfile, outfile, function_log)
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/data_gen/generate_data.py", line 233, in build_data
    create_training_set(inputfile, parameters, outfile, 1, function_log)
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/data_gen/generate_data.py", line 96, in create_training_set
    function_log.write_log("Failed to generate control alignment for: " + aln.windows[i].identifier + '\n Empty file? \n')
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/logger/logger.py", line 31, in write_log
    self.begin_traceback(self.get_log_name())
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/logger/logger.py", line 43, in begin_traceback
    rep_lg = traceback.format_stack()

DEBUG:root:Failed to generate control alignment for: _align_4_3
 Empty file? 

DEBUG:root:Failed to generate control alignment for: _align_4_3
 Empty file? 

Failed to generate control alignment for: _align_4_3
 Empty file? 

MOST RECENT TRACEBACK: 
  File "/home/christopher/anaconda3/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
   File "/home/christopher/anaconda3/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/__main__.py", line 50, in <module>
    main()
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/__main__.py", line 30, in main
    svhip.create_data_set()
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/svhip_object.py", line 46, in create_data_set
    generate_data.testset_cr(self.func_argx, self.inputfile, self.outfile, self.function_log)
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/data_gen/generate_data.py", line 382, in testset_cr
    outfile = build_data(argx, inputfile, outfile, function_log)
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/data_gen/generate_data.py", line 233, in build_data
    create_training_set(inputfile, parameters, outfile, 1, function_log)
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/data_gen/generate_data.py", line 96, in create_training_set
    function_log.write_log("Failed to generate control alignment for: " + aln.windows[i].identifier + '\n Empty file? \n')
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/logger/logger.py", line 31, in write_log
    self.begin_traceback(self.get_log_name())
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/logger/logger.py", line 43, in begin_traceback
    rep_lg = traceback.format_stack()

DEBUG:root:Failed to generate control alignment for: _align_4_4
 Empty file? 

DEBUG:root:Failed to generate control alignment for: _align_4_4
 Empty file? 

Failed to generate control alignment for: _align_4_4
 Empty file? 

MOST RECENT TRACEBACK: 
  File "/home/christopher/anaconda3/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
   File "/home/christopher/anaconda3/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/__main__.py", line 50, in <module>
    main()
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/__main__.py", line 30, in main
    svhip.create_data_set()
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/svhip_object.py", line 46, in create_data_set
    generate_data.testset_cr(self.func_argx, self.inputfile, self.outfile, self.function_log)
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/data_gen/generate_data.py", line 382, in testset_cr
    outfile = build_data(argx, inputfile, outfile, function_log)
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/data_gen/generate_data.py", line 233, in build_data
    create_training_set(inputfile, parameters, outfile, 1, function_log)
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/data_gen/generate_data.py", line 96, in create_training_set
    function_log.write_log("Failed to generate control alignment for: " + aln.windows[i].identifier + '\n Empty file? \n')
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/logger/logger.py", line 31, in write_log
    self.begin_traceback(self.get_log_name())
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/logger/logger.py", line 43, in begin_traceback
    rep_lg = traceback.format_stack()

DEBUG:root:Failed to generate control alignment for: _align_4_5
 Empty file? 

DEBUG:root:Failed to generate control alignment for: _align_4_5
 Empty file? 

Failed to generate control alignment for: _align_4_5
 Empty file? 

MOST RECENT TRACEBACK: 
  File "/home/christopher/anaconda3/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
   File "/home/christopher/anaconda3/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/__main__.py", line 50, in <module>
    main()
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/__main__.py", line 30, in main
    svhip.create_data_set()
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/svhip_object.py", line 46, in create_data_set
    generate_data.testset_cr(self.func_argx, self.inputfile, self.outfile, self.function_log)
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/data_gen/generate_data.py", line 382, in testset_cr
    outfile = build_data(argx, inputfile, outfile, function_log)
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/data_gen/generate_data.py", line 233, in build_data
    create_training_set(inputfile, parameters, outfile, 1, function_log)
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/data_gen/generate_data.py", line 96, in create_training_set
    function_log.write_log("Failed to generate control alignment for: " + aln.windows[i].identifier + '\n Empty file? \n')
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/logger/logger.py", line 31, in write_log
    self.begin_traceback(self.get_log_name())
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/logger/logger.py", line 43, in begin_traceback
    rep_lg = traceback.format_stack()

DEBUG:root:Failed to generate control alignment for: _align_4_6
 Empty file? 

DEBUG:root:Failed to generate control alignment for: _align_4_6
 Empty file? 

Failed to generate control alignment for: _align_4_6
 Empty file? 

MOST RECENT TRACEBACK: 
  File "/home/christopher/anaconda3/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
   File "/home/christopher/anaconda3/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/__main__.py", line 50, in <module>
    main()
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/__main__.py", line 30, in main
    svhip.create_data_set()
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/svhip_object.py", line 46, in create_data_set
    generate_data.testset_cr(self.func_argx, self.inputfile, self.outfile, self.function_log)
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/data_gen/generate_data.py", line 382, in testset_cr
    outfile = build_data(argx, inputfile, outfile, function_log)
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/data_gen/generate_data.py", line 233, in build_data
    create_training_set(inputfile, parameters, outfile, 1, function_log)
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/data_gen/generate_data.py", line 96, in create_training_set
    function_log.write_log("Failed to generate control alignment for: " + aln.windows[i].identifier + '\n Empty file? \n')
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/logger/logger.py", line 31, in write_log
    self.begin_traceback(self.get_log_name())
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/logger/logger.py", line 43, in begin_traceback
    rep_lg = traceback.format_stack()

DEBUG:root:Failed to generate control alignment for: _align_4_7
 Empty file? 

DEBUG:root:Failed to generate control alignment for: _align_4_7
 Empty file? 

Failed to generate control alignment for: _align_4_7
 Empty file? 

MOST RECENT TRACEBACK: 
  File "/home/christopher/anaconda3/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
   File "/home/christopher/anaconda3/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/__main__.py", line 50, in <module>
    main()
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/__main__.py", line 30, in main
    svhip.create_data_set()
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/svhip_object.py", line 46, in create_data_set
    generate_data.testset_cr(self.func_argx, self.inputfile, self.outfile, self.function_log)
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/data_gen/generate_data.py", line 382, in testset_cr
    outfile = build_data(argx, inputfile, outfile, function_log)
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/data_gen/generate_data.py", line 233, in build_data
    create_training_set(inputfile, parameters, outfile, 1, function_log)
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/data_gen/generate_data.py", line 96, in create_training_set
    function_log.write_log("Failed to generate control alignment for: " + aln.windows[i].identifier + '\n Empty file? \n')
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/logger/logger.py", line 31, in write_log
    self.begin_traceback(self.get_log_name())
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/logger/logger.py", line 43, in begin_traceback
    rep_lg = traceback.format_stack()

DEBUG:root:Failed to generate control alignment for: _align_4_8
 Empty file? 

DEBUG:root:Failed to generate control alignment for: _align_4_8
 Empty file? 

Failed to generate control alignment for: _align_4_8
 Empty file? 

MOST RECENT TRACEBACK: 
  File "/home/christopher/anaconda3/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
   File "/home/christopher/anaconda3/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/__main__.py", line 50, in <module>
    main()
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/__main__.py", line 30, in main
    svhip.create_data_set()
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/svhip_object.py", line 46, in create_data_set
    generate_data.testset_cr(self.func_argx, self.inputfile, self.outfile, self.function_log)
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/data_gen/generate_data.py", line 382, in testset_cr
    outfile = build_data(argx, inputfile, outfile, function_log)
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/data_gen/generate_data.py", line 233, in build_data
    create_training_set(inputfile, parameters, outfile, 1, function_log)
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/data_gen/generate_data.py", line 96, in create_training_set
    function_log.write_log("Failed to generate control alignment for: " + aln.windows[i].identifier + '\n Empty file? \n')
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/logger/logger.py", line 31, in write_log
    self.begin_traceback(self.get_log_name())
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/logger/logger.py", line 43, in begin_traceback
    rep_lg = traceback.format_stack()

DEBUG:root:Failed to generate control alignment for: _align_4_9
 Empty file? 

DEBUG:root:Failed to generate control alignment for: _align_4_9
 Empty file? 

Failed to generate control alignment for: _align_4_9
 Empty file? 

MOST RECENT TRACEBACK: 
  File "/home/christopher/anaconda3/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
   File "/home/christopher/anaconda3/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/__main__.py", line 50, in <module>
    main()
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/__main__.py", line 30, in main
    svhip.create_data_set()
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/svhip_object.py", line 46, in create_data_set
    generate_data.testset_cr(self.func_argx, self.inputfile, self.outfile, self.function_log)
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/data_gen/generate_data.py", line 382, in testset_cr
    outfile = build_data(argx, inputfile, outfile, function_log)
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/data_gen/generate_data.py", line 233, in build_data
    create_training_set(inputfile, parameters, outfile, 1, function_log)
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/data_gen/generate_data.py", line 96, in create_training_set
    function_log.write_log("Failed to generate control alignment for: " + aln.windows[i].identifier + '\n Empty file? \n')
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/logger/logger.py", line 31, in write_log
    self.begin_traceback(self.get_log_name())
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/logger/logger.py", line 43, in begin_traceback
    rep_lg = traceback.format_stack()

DEBUG:root:Failed to generate control alignment for: _align_4_10
 Empty file? 

DEBUG:root:Failed to generate control alignment for: _align_4_10
 Empty file? 

Failed to generate control alignment for: _align_4_10
 Empty file? 

MOST RECENT TRACEBACK: 
  File "/home/christopher/anaconda3/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
   File "/home/christopher/anaconda3/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/__main__.py", line 50, in <module>
    main()
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/__main__.py", line 30, in main
    svhip.create_data_set()
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/svhip_object.py", line 46, in create_data_set
    generate_data.testset_cr(self.func_argx, self.inputfile, self.outfile, self.function_log)
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/data_gen/generate_data.py", line 382, in testset_cr
    outfile = build_data(argx, inputfile, outfile, function_log)
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/data_gen/generate_data.py", line 233, in build_data
    create_training_set(inputfile, parameters, outfile, 1, function_log)
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/data_gen/generate_data.py", line 96, in create_training_set
    function_log.write_log("Failed to generate control alignment for: " + aln.windows[i].identifier + '\n Empty file? \n')
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/logger/logger.py", line 31, in write_log
    self.begin_traceback(self.get_log_name())
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/logger/logger.py", line 43, in begin_traceback
    rep_lg = traceback.format_stack()

DEBUG:root:Failed to generate control alignment for: _align_5_1
 Empty file? 

DEBUG:root:Failed to generate control alignment for: _align_5_1
 Empty file? 

Failed to generate control alignment for: _align_5_1
 Empty file? 

MOST RECENT TRACEBACK: 
  File "/home/christopher/anaconda3/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
   File "/home/christopher/anaconda3/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/__main__.py", line 50, in <module>
    main()
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/__main__.py", line 30, in main
    svhip.create_data_set()
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/svhip_object.py", line 46, in create_data_set
    generate_data.testset_cr(self.func_argx, self.inputfile, self.outfile, self.function_log)
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/data_gen/generate_data.py", line 382, in testset_cr
    outfile = build_data(argx, inputfile, outfile, function_log)
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/data_gen/generate_data.py", line 233, in build_data
    create_training_set(inputfile, parameters, outfile, 1, function_log)
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/data_gen/generate_data.py", line 96, in create_training_set
    function_log.write_log("Failed to generate control alignment for: " + aln.windows[i].identifier + '\n Empty file? \n')
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/logger/logger.py", line 31, in write_log
    self.begin_traceback(self.get_log_name())
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/logger/logger.py", line 43, in begin_traceback
    rep_lg = traceback.format_stack()

DEBUG:root:Failed to generate control alignment for: _align_5_2
 Empty file? 

DEBUG:root:Failed to generate control alignment for: _align_5_2
 Empty file? 

Failed to generate control alignment for: _align_5_2
 Empty file? 

MOST RECENT TRACEBACK: 
  File "/home/christopher/anaconda3/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
   File "/home/christopher/anaconda3/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/__main__.py", line 50, in <module>
    main()
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/__main__.py", line 30, in main
    svhip.create_data_set()
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/svhip_object.py", line 46, in create_data_set
    generate_data.testset_cr(self.func_argx, self.inputfile, self.outfile, self.function_log)
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/data_gen/generate_data.py", line 382, in testset_cr
    outfile = build_data(argx, inputfile, outfile, function_log)
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/data_gen/generate_data.py", line 233, in build_data
    create_training_set(inputfile, parameters, outfile, 1, function_log)
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/data_gen/generate_data.py", line 96, in create_training_set
    function_log.write_log("Failed to generate control alignment for: " + aln.windows[i].identifier + '\n Empty file? \n')
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/logger/logger.py", line 31, in write_log
    self.begin_traceback(self.get_log_name())
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/logger/logger.py", line 43, in begin_traceback
    rep_lg = traceback.format_stack()

DEBUG:root:Failed to generate control alignment for: _align_5_3
 Empty file? 

DEBUG:root:Failed to generate control alignment for: _align_5_3
 Empty file? 

Failed to generate control alignment for: _align_5_3
 Empty file? 

MOST RECENT TRACEBACK: 
  File "/home/christopher/anaconda3/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
   File "/home/christopher/anaconda3/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/__main__.py", line 50, in <module>
    main()
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/__main__.py", line 30, in main
    svhip.create_data_set()
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/svhip_object.py", line 46, in create_data_set
    generate_data.testset_cr(self.func_argx, self.inputfile, self.outfile, self.function_log)
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/data_gen/generate_data.py", line 382, in testset_cr
    outfile = build_data(argx, inputfile, outfile, function_log)
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/data_gen/generate_data.py", line 233, in build_data
    create_training_set(inputfile, parameters, outfile, 1, function_log)
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/data_gen/generate_data.py", line 96, in create_training_set
    function_log.write_log("Failed to generate control alignment for: " + aln.windows[i].identifier + '\n Empty file? \n')
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/logger/logger.py", line 31, in write_log
    self.begin_traceback(self.get_log_name())
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/logger/logger.py", line 43, in begin_traceback
    rep_lg = traceback.format_stack()

DEBUG:root:Failed to generate control alignment for: _align_5_4
 Empty file? 

DEBUG:root:Failed to generate control alignment for: _align_5_4
 Empty file? 

Failed to generate control alignment for: _align_5_4
 Empty file? 

MOST RECENT TRACEBACK: 
  File "/home/christopher/anaconda3/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
   File "/home/christopher/anaconda3/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/__main__.py", line 50, in <module>
    main()
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/__main__.py", line 30, in main
    svhip.create_data_set()
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/svhip_object.py", line 46, in create_data_set
    generate_data.testset_cr(self.func_argx, self.inputfile, self.outfile, self.function_log)
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/data_gen/generate_data.py", line 382, in testset_cr
    outfile = build_data(argx, inputfile, outfile, function_log)
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/data_gen/generate_data.py", line 233, in build_data
    create_training_set(inputfile, parameters, outfile, 1, function_log)
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/data_gen/generate_data.py", line 96, in create_training_set
    function_log.write_log("Failed to generate control alignment for: " + aln.windows[i].identifier + '\n Empty file? \n')
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/logger/logger.py", line 31, in write_log
    self.begin_traceback(self.get_log_name())
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/logger/logger.py", line 43, in begin_traceback
    rep_lg = traceback.format_stack()

DEBUG:root:Failed to generate control alignment for: _align_5_5
 Empty file? 

DEBUG:root:Failed to generate control alignment for: _align_5_5
 Empty file? 

Failed to generate control alignment for: _align_5_5
 Empty file? 

MOST RECENT TRACEBACK: 
  File "/home/christopher/anaconda3/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
   File "/home/christopher/anaconda3/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/__main__.py", line 50, in <module>
    main()
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/__main__.py", line 30, in main
    svhip.create_data_set()
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/svhip_object.py", line 46, in create_data_set
    generate_data.testset_cr(self.func_argx, self.inputfile, self.outfile, self.function_log)
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/data_gen/generate_data.py", line 382, in testset_cr
    outfile = build_data(argx, inputfile, outfile, function_log)
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/data_gen/generate_data.py", line 233, in build_data
    create_training_set(inputfile, parameters, outfile, 1, function_log)
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/data_gen/generate_data.py", line 96, in create_training_set
    function_log.write_log("Failed to generate control alignment for: " + aln.windows[i].identifier + '\n Empty file? \n')
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/logger/logger.py", line 31, in write_log
    self.begin_traceback(self.get_log_name())
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/logger/logger.py", line 43, in begin_traceback
    rep_lg = traceback.format_stack()

DEBUG:root:Failed to generate control alignment for: _align_5_6
 Empty file? 

DEBUG:root:Failed to generate control alignment for: _align_5_6
 Empty file? 

Failed to generate control alignment for: _align_5_6
 Empty file? 

MOST RECENT TRACEBACK: 
  File "/home/christopher/anaconda3/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
   File "/home/christopher/anaconda3/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/__main__.py", line 50, in <module>
    main()
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/__main__.py", line 30, in main
    svhip.create_data_set()
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/svhip_object.py", line 46, in create_data_set
    generate_data.testset_cr(self.func_argx, self.inputfile, self.outfile, self.function_log)
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/data_gen/generate_data.py", line 382, in testset_cr
    outfile = build_data(argx, inputfile, outfile, function_log)
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/data_gen/generate_data.py", line 233, in build_data
    create_training_set(inputfile, parameters, outfile, 1, function_log)
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/data_gen/generate_data.py", line 96, in create_training_set
    function_log.write_log("Failed to generate control alignment for: " + aln.windows[i].identifier + '\n Empty file? \n')
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/logger/logger.py", line 31, in write_log
    self.begin_traceback(self.get_log_name())
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/logger/logger.py", line 43, in begin_traceback
    rep_lg = traceback.format_stack()

DEBUG:root:Failed to generate control alignment for: _align_5_7
 Empty file? 

DEBUG:root:Failed to generate control alignment for: _align_5_7
 Empty file? 

Failed to generate control alignment for: _align_5_7
 Empty file? 

MOST RECENT TRACEBACK: 
  File "/home/christopher/anaconda3/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
   File "/home/christopher/anaconda3/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/__main__.py", line 50, in <module>
    main()
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/__main__.py", line 30, in main
    svhip.create_data_set()
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/svhip_object.py", line 46, in create_data_set
    generate_data.testset_cr(self.func_argx, self.inputfile, self.outfile, self.function_log)
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/data_gen/generate_data.py", line 382, in testset_cr
    outfile = build_data(argx, inputfile, outfile, function_log)
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/data_gen/generate_data.py", line 233, in build_data
    create_training_set(inputfile, parameters, outfile, 1, function_log)
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/data_gen/generate_data.py", line 96, in create_training_set
    function_log.write_log("Failed to generate control alignment for: " + aln.windows[i].identifier + '\n Empty file? \n')
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/logger/logger.py", line 31, in write_log
    self.begin_traceback(self.get_log_name())
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/logger/logger.py", line 43, in begin_traceback
    rep_lg = traceback.format_stack()

DEBUG:root:Failed to generate control alignment for: _align_5_8
 Empty file? 

DEBUG:root:Failed to generate control alignment for: _align_5_8
 Empty file? 

Failed to generate control alignment for: _align_5_8
 Empty file? 

MOST RECENT TRACEBACK: 
  File "/home/christopher/anaconda3/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
   File "/home/christopher/anaconda3/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/__main__.py", line 50, in <module>
    main()
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/__main__.py", line 30, in main
    svhip.create_data_set()
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/svhip_object.py", line 46, in create_data_set
    generate_data.testset_cr(self.func_argx, self.inputfile, self.outfile, self.function_log)
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/data_gen/generate_data.py", line 382, in testset_cr
    outfile = build_data(argx, inputfile, outfile, function_log)
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/data_gen/generate_data.py", line 233, in build_data
    create_training_set(inputfile, parameters, outfile, 1, function_log)
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/data_gen/generate_data.py", line 96, in create_training_set
    function_log.write_log("Failed to generate control alignment for: " + aln.windows[i].identifier + '\n Empty file? \n')
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/logger/logger.py", line 31, in write_log
    self.begin_traceback(self.get_log_name())
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/logger/logger.py", line 43, in begin_traceback
    rep_lg = traceback.format_stack()

DEBUG:root:Failed to generate control alignment for: _align_5_9
 Empty file? 

DEBUG:root:Failed to generate control alignment for: _align_5_9
 Empty file? 

Failed to generate control alignment for: _align_5_9
 Empty file? 

MOST RECENT TRACEBACK: 
  File "/home/christopher/anaconda3/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
   File "/home/christopher/anaconda3/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/__main__.py", line 50, in <module>
    main()
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/__main__.py", line 30, in main
    svhip.create_data_set()
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/svhip_object.py", line 46, in create_data_set
    generate_data.testset_cr(self.func_argx, self.inputfile, self.outfile, self.function_log)
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/data_gen/generate_data.py", line 382, in testset_cr
    outfile = build_data(argx, inputfile, outfile, function_log)
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/data_gen/generate_data.py", line 233, in build_data
    create_training_set(inputfile, parameters, outfile, 1, function_log)
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/data_gen/generate_data.py", line 96, in create_training_set
    function_log.write_log("Failed to generate control alignment for: " + aln.windows[i].identifier + '\n Empty file? \n')
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/logger/logger.py", line 31, in write_log
    self.begin_traceback(self.get_log_name())
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/logger/logger.py", line 43, in begin_traceback
    rep_lg = traceback.format_stack()

DEBUG:root:Failed to generate control alignment for: _align_5_10
 Empty file? 

DEBUG:root:Failed to generate control alignment for: _align_5_10
 Empty file? 

Failed to generate control alignment for: _align_5_10
 Empty file? 

MOST RECENT TRACEBACK: 
  File "/home/christopher/anaconda3/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
   File "/home/christopher/anaconda3/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/__main__.py", line 50, in <module>
    main()
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/__main__.py", line 30, in main
    svhip.create_data_set()
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/svhip_object.py", line 46, in create_data_set
    generate_data.testset_cr(self.func_argx, self.inputfile, self.outfile, self.function_log)
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/data_gen/generate_data.py", line 382, in testset_cr
    outfile = build_data(argx, inputfile, outfile, function_log)
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/data_gen/generate_data.py", line 233, in build_data
    create_training_set(inputfile, parameters, outfile, 1, function_log)
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/data_gen/generate_data.py", line 96, in create_training_set
    function_log.write_log("Failed to generate control alignment for: " + aln.windows[i].identifier + '\n Empty file? \n')
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/logger/logger.py", line 31, in write_log
    self.begin_traceback(self.get_log_name())
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/logger/logger.py", line 43, in begin_traceback
    rep_lg = traceback.format_stack()

DEBUG:root:Failed to generate control alignment for: _align_6_1
 Empty file? 

DEBUG:root:Failed to generate control alignment for: _align_6_1
 Empty file? 

Failed to generate control alignment for: _align_6_1
 Empty file? 

MOST RECENT TRACEBACK: 
  File "/home/christopher/anaconda3/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
   File "/home/christopher/anaconda3/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/__main__.py", line 50, in <module>
    main()
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/__main__.py", line 30, in main
    svhip.create_data_set()
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/svhip_object.py", line 46, in create_data_set
    generate_data.testset_cr(self.func_argx, self.inputfile, self.outfile, self.function_log)
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/data_gen/generate_data.py", line 382, in testset_cr
    outfile = build_data(argx, inputfile, outfile, function_log)
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/data_gen/generate_data.py", line 233, in build_data
    create_training_set(inputfile, parameters, outfile, 1, function_log)
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/data_gen/generate_data.py", line 96, in create_training_set
    function_log.write_log("Failed to generate control alignment for: " + aln.windows[i].identifier + '\n Empty file? \n')
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/logger/logger.py", line 31, in write_log
    self.begin_traceback(self.get_log_name())
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/logger/logger.py", line 43, in begin_traceback
    rep_lg = traceback.format_stack()

DEBUG:root:Failed to generate control alignment for: _align_6_2
 Empty file? 

DEBUG:root:Failed to generate control alignment for: _align_6_2
 Empty file? 

Failed to generate control alignment for: _align_6_2
 Empty file? 

MOST RECENT TRACEBACK: 
  File "/home/christopher/anaconda3/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
   File "/home/christopher/anaconda3/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/__main__.py", line 50, in <module>
    main()
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/__main__.py", line 30, in main
    svhip.create_data_set()
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/svhip_object.py", line 46, in create_data_set
    generate_data.testset_cr(self.func_argx, self.inputfile, self.outfile, self.function_log)
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/data_gen/generate_data.py", line 382, in testset_cr
    outfile = build_data(argx, inputfile, outfile, function_log)
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/data_gen/generate_data.py", line 233, in build_data
    create_training_set(inputfile, parameters, outfile, 1, function_log)
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/data_gen/generate_data.py", line 96, in create_training_set
    function_log.write_log("Failed to generate control alignment for: " + aln.windows[i].identifier + '\n Empty file? \n')
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/logger/logger.py", line 31, in write_log
    self.begin_traceback(self.get_log_name())
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/logger/logger.py", line 43, in begin_traceback
    rep_lg = traceback.format_stack()

DEBUG:root:Failed to generate control alignment for: _align_6_3
 Empty file? 

DEBUG:root:Failed to generate control alignment for: _align_6_3
 Empty file? 

Failed to generate control alignment for: _align_6_3
 Empty file? 

MOST RECENT TRACEBACK: 
  File "/home/christopher/anaconda3/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
   File "/home/christopher/anaconda3/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/__main__.py", line 50, in <module>
    main()
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/__main__.py", line 30, in main
    svhip.create_data_set()
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/svhip_object.py", line 46, in create_data_set
    generate_data.testset_cr(self.func_argx, self.inputfile, self.outfile, self.function_log)
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/data_gen/generate_data.py", line 382, in testset_cr
    outfile = build_data(argx, inputfile, outfile, function_log)
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/data_gen/generate_data.py", line 233, in build_data
    create_training_set(inputfile, parameters, outfile, 1, function_log)
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/data_gen/generate_data.py", line 96, in create_training_set
    function_log.write_log("Failed to generate control alignment for: " + aln.windows[i].identifier + '\n Empty file? \n')
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/logger/logger.py", line 31, in write_log
    self.begin_traceback(self.get_log_name())
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/logger/logger.py", line 43, in begin_traceback
    rep_lg = traceback.format_stack()

DEBUG:root:Failed to generate control alignment for: _align_6_4
 Empty file? 

DEBUG:root:Failed to generate control alignment for: _align_6_4
 Empty file? 

Failed to generate control alignment for: _align_6_4
 Empty file? 

MOST RECENT TRACEBACK: 
  File "/home/christopher/anaconda3/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
   File "/home/christopher/anaconda3/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/__main__.py", line 50, in <module>
    main()
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/__main__.py", line 30, in main
    svhip.create_data_set()
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/svhip_object.py", line 46, in create_data_set
    generate_data.testset_cr(self.func_argx, self.inputfile, self.outfile, self.function_log)
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/data_gen/generate_data.py", line 382, in testset_cr
    outfile = build_data(argx, inputfile, outfile, function_log)
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/data_gen/generate_data.py", line 233, in build_data
    create_training_set(inputfile, parameters, outfile, 1, function_log)
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/data_gen/generate_data.py", line 96, in create_training_set
    function_log.write_log("Failed to generate control alignment for: " + aln.windows[i].identifier + '\n Empty file? \n')
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/logger/logger.py", line 31, in write_log
    self.begin_traceback(self.get_log_name())
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/logger/logger.py", line 43, in begin_traceback
    rep_lg = traceback.format_stack()

DEBUG:root:Failed to generate control alignment for: _align_6_5
 Empty file? 

DEBUG:root:Failed to generate control alignment for: _align_6_5
 Empty file? 

Failed to generate control alignment for: _align_6_5
 Empty file? 

MOST RECENT TRACEBACK: 
  File "/home/christopher/anaconda3/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
   File "/home/christopher/anaconda3/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/__main__.py", line 50, in <module>
    main()
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/__main__.py", line 30, in main
    svhip.create_data_set()
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/svhip_object.py", line 46, in create_data_set
    generate_data.testset_cr(self.func_argx, self.inputfile, self.outfile, self.function_log)
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/data_gen/generate_data.py", line 382, in testset_cr
    outfile = build_data(argx, inputfile, outfile, function_log)
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/data_gen/generate_data.py", line 233, in build_data
    create_training_set(inputfile, parameters, outfile, 1, function_log)
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/data_gen/generate_data.py", line 96, in create_training_set
    function_log.write_log("Failed to generate control alignment for: " + aln.windows[i].identifier + '\n Empty file? \n')
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/logger/logger.py", line 31, in write_log
    self.begin_traceback(self.get_log_name())
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/logger/logger.py", line 43, in begin_traceback
    rep_lg = traceback.format_stack()

DEBUG:root:Failed to generate control alignment for: _align_6_6
 Empty file? 

DEBUG:root:Failed to generate control alignment for: _align_6_6
 Empty file? 

Failed to generate control alignment for: _align_6_6
 Empty file? 

MOST RECENT TRACEBACK: 
  File "/home/christopher/anaconda3/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
   File "/home/christopher/anaconda3/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/__main__.py", line 50, in <module>
    main()
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/__main__.py", line 30, in main
    svhip.create_data_set()
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/svhip_object.py", line 46, in create_data_set
    generate_data.testset_cr(self.func_argx, self.inputfile, self.outfile, self.function_log)
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/data_gen/generate_data.py", line 382, in testset_cr
    outfile = build_data(argx, inputfile, outfile, function_log)
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/data_gen/generate_data.py", line 233, in build_data
    create_training_set(inputfile, parameters, outfile, 1, function_log)
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/data_gen/generate_data.py", line 96, in create_training_set
    function_log.write_log("Failed to generate control alignment for: " + aln.windows[i].identifier + '\n Empty file? \n')
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/logger/logger.py", line 31, in write_log
    self.begin_traceback(self.get_log_name())
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/logger/logger.py", line 43, in begin_traceback
    rep_lg = traceback.format_stack()

DEBUG:root:Failed to generate control alignment for: _align_6_7
 Empty file? 

DEBUG:root:Failed to generate control alignment for: _align_6_7
 Empty file? 

Failed to generate control alignment for: _align_6_7
 Empty file? 

MOST RECENT TRACEBACK: 
  File "/home/christopher/anaconda3/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
   File "/home/christopher/anaconda3/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/__main__.py", line 50, in <module>
    main()
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/__main__.py", line 30, in main
    svhip.create_data_set()
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/svhip_object.py", line 46, in create_data_set
    generate_data.testset_cr(self.func_argx, self.inputfile, self.outfile, self.function_log)
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/data_gen/generate_data.py", line 382, in testset_cr
    outfile = build_data(argx, inputfile, outfile, function_log)
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/data_gen/generate_data.py", line 233, in build_data
    create_training_set(inputfile, parameters, outfile, 1, function_log)
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/data_gen/generate_data.py", line 96, in create_training_set
    function_log.write_log("Failed to generate control alignment for: " + aln.windows[i].identifier + '\n Empty file? \n')
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/logger/logger.py", line 31, in write_log
    self.begin_traceback(self.get_log_name())
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/logger/logger.py", line 43, in begin_traceback
    rep_lg = traceback.format_stack()

DEBUG:root:Failed to generate control alignment for: _align_6_8
 Empty file? 

DEBUG:root:Failed to generate control alignment for: _align_6_8
 Empty file? 

Failed to generate control alignment for: _align_6_8
 Empty file? 

MOST RECENT TRACEBACK: 
  File "/home/christopher/anaconda3/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
   File "/home/christopher/anaconda3/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/__main__.py", line 50, in <module>
    main()
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/__main__.py", line 30, in main
    svhip.create_data_set()
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/svhip_object.py", line 46, in create_data_set
    generate_data.testset_cr(self.func_argx, self.inputfile, self.outfile, self.function_log)
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/data_gen/generate_data.py", line 382, in testset_cr
    outfile = build_data(argx, inputfile, outfile, function_log)
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/data_gen/generate_data.py", line 233, in build_data
    create_training_set(inputfile, parameters, outfile, 1, function_log)
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/data_gen/generate_data.py", line 96, in create_training_set
    function_log.write_log("Failed to generate control alignment for: " + aln.windows[i].identifier + '\n Empty file? \n')
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/logger/logger.py", line 31, in write_log
    self.begin_traceback(self.get_log_name())
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/logger/logger.py", line 43, in begin_traceback
    rep_lg = traceback.format_stack()

DEBUG:root:Failed to generate control alignment for: _align_6_9
 Empty file? 

DEBUG:root:Failed to generate control alignment for: _align_6_9
 Empty file? 

Failed to generate control alignment for: _align_6_9
 Empty file? 

MOST RECENT TRACEBACK: 
  File "/home/christopher/anaconda3/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
   File "/home/christopher/anaconda3/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/__main__.py", line 50, in <module>
    main()
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/__main__.py", line 30, in main
    svhip.create_data_set()
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/svhip_object.py", line 46, in create_data_set
    generate_data.testset_cr(self.func_argx, self.inputfile, self.outfile, self.function_log)
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/data_gen/generate_data.py", line 382, in testset_cr
    outfile = build_data(argx, inputfile, outfile, function_log)
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/data_gen/generate_data.py", line 233, in build_data
    create_training_set(inputfile, parameters, outfile, 1, function_log)
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/data_gen/generate_data.py", line 96, in create_training_set
    function_log.write_log("Failed to generate control alignment for: " + aln.windows[i].identifier + '\n Empty file? \n')
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/logger/logger.py", line 31, in write_log
    self.begin_traceback(self.get_log_name())
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/logger/logger.py", line 43, in begin_traceback
    rep_lg = traceback.format_stack()

DEBUG:root:Failed to generate control alignment for: _align_6_10
 Empty file? 

DEBUG:root:Failed to generate control alignment for: _align_6_10
 Empty file? 

Failed to generate control alignment for: _align_6_10
 Empty file? 

MOST RECENT TRACEBACK: 
  File "/home/christopher/anaconda3/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
   File "/home/christopher/anaconda3/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/__main__.py", line 50, in <module>
    main()
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/__main__.py", line 30, in main
    svhip.create_data_set()
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/svhip_object.py", line 46, in create_data_set
    generate_data.testset_cr(self.func_argx, self.inputfile, self.outfile, self.function_log)
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/data_gen/generate_data.py", line 382, in testset_cr
    outfile = build_data(argx, inputfile, outfile, function_log)
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/data_gen/generate_data.py", line 233, in build_data
    create_training_set(inputfile, parameters, outfile, 1, function_log)
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/data_gen/generate_data.py", line 96, in create_training_set
    function_log.write_log("Failed to generate control alignment for: " + aln.windows[i].identifier + '\n Empty file? \n')
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/logger/logger.py", line 31, in write_log
    self.begin_traceback(self.get_log_name())
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/logger/logger.py", line 43, in begin_traceback
    rep_lg = traceback.format_stack()

DEBUG:root:Failed to generate control alignment for: _align_7_1
 Empty file? 

DEBUG:root:Failed to generate control alignment for: _align_7_1
 Empty file? 

Failed to generate control alignment for: _align_7_1
 Empty file? 

MOST RECENT TRACEBACK: 
  File "/home/christopher/anaconda3/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
   File "/home/christopher/anaconda3/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/__main__.py", line 50, in <module>
    main()
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/__main__.py", line 30, in main
    svhip.create_data_set()
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/svhip_object.py", line 46, in create_data_set
    generate_data.testset_cr(self.func_argx, self.inputfile, self.outfile, self.function_log)
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/data_gen/generate_data.py", line 382, in testset_cr
    outfile = build_data(argx, inputfile, outfile, function_log)
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/data_gen/generate_data.py", line 233, in build_data
    create_training_set(inputfile, parameters, outfile, 1, function_log)
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/data_gen/generate_data.py", line 96, in create_training_set
    function_log.write_log("Failed to generate control alignment for: " + aln.windows[i].identifier + '\n Empty file? \n')
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/logger/logger.py", line 31, in write_log
    self.begin_traceback(self.get_log_name())
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/logger/logger.py", line 43, in begin_traceback
    rep_lg = traceback.format_stack()

DEBUG:root:Failed to generate control alignment for: _align_7_2
 Empty file? 

DEBUG:root:Failed to generate control alignment for: _align_7_2
 Empty file? 

Failed to generate control alignment for: _align_7_2
 Empty file? 

MOST RECENT TRACEBACK: 
  File "/home/christopher/anaconda3/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
   File "/home/christopher/anaconda3/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/__main__.py", line 50, in <module>
    main()
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/__main__.py", line 30, in main
    svhip.create_data_set()
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/svhip_object.py", line 46, in create_data_set
    generate_data.testset_cr(self.func_argx, self.inputfile, self.outfile, self.function_log)
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/data_gen/generate_data.py", line 382, in testset_cr
    outfile = build_data(argx, inputfile, outfile, function_log)
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/data_gen/generate_data.py", line 233, in build_data
    create_training_set(inputfile, parameters, outfile, 1, function_log)
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/data_gen/generate_data.py", line 96, in create_training_set
    function_log.write_log("Failed to generate control alignment for: " + aln.windows[i].identifier + '\n Empty file? \n')
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/logger/logger.py", line 31, in write_log
    self.begin_traceback(self.get_log_name())
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/logger/logger.py", line 43, in begin_traceback
    rep_lg = traceback.format_stack()

DEBUG:root:Failed to generate control alignment for: _align_7_3
 Empty file? 

DEBUG:root:Failed to generate control alignment for: _align_7_3
 Empty file? 

Failed to generate control alignment for: _align_7_3
 Empty file? 

MOST RECENT TRACEBACK: 
  File "/home/christopher/anaconda3/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
   File "/home/christopher/anaconda3/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/__main__.py", line 50, in <module>
    main()
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/__main__.py", line 30, in main
    svhip.create_data_set()
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/svhip_object.py", line 46, in create_data_set
    generate_data.testset_cr(self.func_argx, self.inputfile, self.outfile, self.function_log)
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/data_gen/generate_data.py", line 382, in testset_cr
    outfile = build_data(argx, inputfile, outfile, function_log)
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/data_gen/generate_data.py", line 233, in build_data
    create_training_set(inputfile, parameters, outfile, 1, function_log)
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/data_gen/generate_data.py", line 96, in create_training_set
    function_log.write_log("Failed to generate control alignment for: " + aln.windows[i].identifier + '\n Empty file? \n')
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/logger/logger.py", line 31, in write_log
    self.begin_traceback(self.get_log_name())
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/logger/logger.py", line 43, in begin_traceback
    rep_lg = traceback.format_stack()

DEBUG:root:Failed to generate control alignment for: _align_7_4
 Empty file? 

DEBUG:root:Failed to generate control alignment for: _align_7_4
 Empty file? 

Failed to generate control alignment for: _align_7_4
 Empty file? 

MOST RECENT TRACEBACK: 
  File "/home/christopher/anaconda3/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
   File "/home/christopher/anaconda3/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/__main__.py", line 50, in <module>
    main()
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/__main__.py", line 30, in main
    svhip.create_data_set()
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/svhip_object.py", line 46, in create_data_set
    generate_data.testset_cr(self.func_argx, self.inputfile, self.outfile, self.function_log)
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/data_gen/generate_data.py", line 382, in testset_cr
    outfile = build_data(argx, inputfile, outfile, function_log)
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/data_gen/generate_data.py", line 233, in build_data
    create_training_set(inputfile, parameters, outfile, 1, function_log)
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/data_gen/generate_data.py", line 96, in create_training_set
    function_log.write_log("Failed to generate control alignment for: " + aln.windows[i].identifier + '\n Empty file? \n')
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/logger/logger.py", line 31, in write_log
    self.begin_traceback(self.get_log_name())
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/logger/logger.py", line 43, in begin_traceback
    rep_lg = traceback.format_stack()

DEBUG:root:Failed to generate control alignment for: _align_7_5
 Empty file? 

DEBUG:root:Failed to generate control alignment for: _align_7_5
 Empty file? 

Failed to generate control alignment for: _align_7_5
 Empty file? 

MOST RECENT TRACEBACK: 
  File "/home/christopher/anaconda3/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
   File "/home/christopher/anaconda3/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/__main__.py", line 50, in <module>
    main()
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/__main__.py", line 30, in main
    svhip.create_data_set()
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/svhip_object.py", line 46, in create_data_set
    generate_data.testset_cr(self.func_argx, self.inputfile, self.outfile, self.function_log)
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/data_gen/generate_data.py", line 382, in testset_cr
    outfile = build_data(argx, inputfile, outfile, function_log)
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/data_gen/generate_data.py", line 233, in build_data
    create_training_set(inputfile, parameters, outfile, 1, function_log)
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/data_gen/generate_data.py", line 96, in create_training_set
    function_log.write_log("Failed to generate control alignment for: " + aln.windows[i].identifier + '\n Empty file? \n')
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/logger/logger.py", line 31, in write_log
    self.begin_traceback(self.get_log_name())
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/logger/logger.py", line 43, in begin_traceback
    rep_lg = traceback.format_stack()

DEBUG:root:Failed to generate control alignment for: _align_7_6
 Empty file? 

DEBUG:root:Failed to generate control alignment for: _align_7_6
 Empty file? 

Failed to generate control alignment for: _align_7_6
 Empty file? 

MOST RECENT TRACEBACK: 
  File "/home/christopher/anaconda3/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
   File "/home/christopher/anaconda3/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/__main__.py", line 50, in <module>
    main()
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/__main__.py", line 30, in main
    svhip.create_data_set()
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/svhip_object.py", line 46, in create_data_set
    generate_data.testset_cr(self.func_argx, self.inputfile, self.outfile, self.function_log)
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/data_gen/generate_data.py", line 382, in testset_cr
    outfile = build_data(argx, inputfile, outfile, function_log)
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/data_gen/generate_data.py", line 233, in build_data
    create_training_set(inputfile, parameters, outfile, 1, function_log)
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/data_gen/generate_data.py", line 96, in create_training_set
    function_log.write_log("Failed to generate control alignment for: " + aln.windows[i].identifier + '\n Empty file? \n')
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/logger/logger.py", line 31, in write_log
    self.begin_traceback(self.get_log_name())
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/logger/logger.py", line 43, in begin_traceback
    rep_lg = traceback.format_stack()

DEBUG:root:Failed to generate control alignment for: _align_7_7
 Empty file? 

DEBUG:root:Failed to generate control alignment for: _align_7_7
 Empty file? 

Failed to generate control alignment for: _align_7_7
 Empty file? 

MOST RECENT TRACEBACK: 
  File "/home/christopher/anaconda3/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
   File "/home/christopher/anaconda3/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/__main__.py", line 50, in <module>
    main()
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/__main__.py", line 30, in main
    svhip.create_data_set()
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/svhip_object.py", line 46, in create_data_set
    generate_data.testset_cr(self.func_argx, self.inputfile, self.outfile, self.function_log)
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/data_gen/generate_data.py", line 382, in testset_cr
    outfile = build_data(argx, inputfile, outfile, function_log)
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/data_gen/generate_data.py", line 233, in build_data
    create_training_set(inputfile, parameters, outfile, 1, function_log)
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/data_gen/generate_data.py", line 96, in create_training_set
    function_log.write_log("Failed to generate control alignment for: " + aln.windows[i].identifier + '\n Empty file? \n')
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/logger/logger.py", line 31, in write_log
    self.begin_traceback(self.get_log_name())
   File "/home/christopher/Development/Code_Workshop/Svhip_development/svhip_Dev/svhip/logger/logger.py", line 43, in begin_traceback
    rep_lg = traceback.format_stack()

